add mysql backend
Tongsuo-Project/RustyVault pull request #46
Opened 2024-03-11 03:44 UTC by WorldWay

2024-03-11 03:46 UTC, WorldWay commented
add mysql backend feature

1.not yet support the ssl way connecting to mysql
2.has already pass the unit test

2024-03-25 00:44 UTC, wa5i requested changes
There is a conflict in Cargo.toml that needs to be resolved.

2024-03-26 08:24 UTC, WorldWay commented on src/storage/mysql/mod.rs
> +    println!("database_url: {}", database_url);
got it

2024-03-26 08:24 UTC, WorldWay commented on src/storage/mysql/mod.rs
> +            println!("Error: {:?}", e);
got it

2024-03-26 08:27 UTC, WorldWay commented on src/storage/mysql/mysql_backend.rs
> +pub struct NewMysqlBackendEntry {
It is the common usage of the orm-framework diesel to use two different struct for inserting and selection, in this scence, these two structs are same, I'll have a try to use the same one to solve it

2024-03-26 08:57 UTC, WorldWay commented
@wa5i  I have fix these problems, let the workflow run please

2024-03-27 07:46 UTC, merged